"""FrontierSplit Network Protocol: Wire formats and tensor serialization."""

from __future__ import annotations

import base64
import time
from typing import Dict, List, Optional
import numpy as np
from pydantic import BaseModel, Field


class ActivationPacket(BaseModel):
    """The inter-node payload passed along the pipeline chain."""
    request_id: str
    sequence_step: int
    stage_id: int
    is_prefill: bool = False
    tokens: Optional[List[int]] = None
    tensor_shape: List[int] = Field(default_factory=list)
    tensor_dtype: str = "float32"
    tensor_bytes_b64: str = ""
    timestamp_sent_ms: float = Field(default_factory=lambda: time.time() * 1000)
    stage_timings: Dict[str, float] = Field(default_factory=dict)

    def set_tensor(self, arr: np.ndarray) -> None:
        """Serialize a numpy tensor into base64 raw bytes."""
        self.tensor_shape = list(arr.shape)
        self.tensor_dtype = str(arr.dtype)
        raw_bytes = arr.tobytes()
        self.tensor_bytes_b64 = base64.b64encode(raw_bytes).decode("ascii")

    def get_tensor(self) -> np.ndarray:
        """Deserialize raw base64 bytes back into a numpy array."""
        if not self.tensor_bytes_b64:
            return np.zeros(self.tensor_shape, dtype=self.tensor_dtype)
        raw_bytes = base64.b64decode(self.tensor_bytes_b64.encode("ascii"))
        return np.frombuffer(raw_bytes, dtype=self.tensor_dtype).reshape(self.tensor_shape)


class GenerationResponse(BaseModel):
    """Output packet generated by the final node in the pipeline."""
    request_id: str
    token_id: int
    text: str
    is_finished: bool
    latency_ms: float
    stage_timings: Dict[str, float] = Field(default_factory=dict)


class BatchedActivationPacket(BaseModel):
    """Inter-node payload containing multiple requests batched into a single forward pass."""
    request_ids: List[str]
    sequence_steps: List[int]
    stage_id: int
    is_prefill: bool = False
    tokens_batch: Optional[List[List[int]]] = None  # Padded tokens per request [B, max_len]
    attention_mask: Optional[List[List[int]]] = None # Attention mask per request [B, max_len]
    tensor_shape: List[int] = Field(default_factory=list) # [B, max_len, hidden_size]
    tensor_dtype: str = "float32"
    tensor_bytes_b64: str = ""
    timestamp_sent_ms: float = Field(default_factory=lambda: time.time() * 1000)
    stage_timings: Dict[str, float] = Field(default_factory=dict)

    def set_tensor(self, arr: np.ndarray) -> None:
        """Serialize a numpy tensor into base64 raw bytes."""
        self.tensor_shape = list(arr.shape)
        self.tensor_dtype = str(arr.dtype)
        raw_bytes = arr.tobytes()
        self.tensor_bytes_b64 = base64.b64encode(raw_bytes).decode("ascii")

    def get_tensor(self) -> np.ndarray:
        """Deserialize raw base64 bytes back into a numpy array."""
        if not self.tensor_bytes_b64:
            return np.zeros(self.tensor_shape, dtype=self.tensor_dtype)
        raw_bytes = base64.b64decode(self.tensor_bytes_b64.encode("ascii"))
        return np.frombuffer(raw_bytes, dtype=self.tensor_dtype).reshape(self.tensor_shape)


class BatchedGenerationResponse(BaseModel):
    """Output packet generated by the final node containing responses for all requests in batch."""
    responses: List[GenerationResponse]
    batch_size: int
    stage_timings: Dict[str, float] = Field(default_factory=dict)


